### ISSUE TITLE
Vulnerable to attacks that set the wrong Host header

### ISSUE THREAD

**Issue by petschekr** [HackGT/auth#1]
By using the raw `Host` header, an attacker can make the user visit an entirely different site for auth. The current implementation also assumes that the app is being hosted on port 80 or 443.
Relevant section from the API code:
https://github.com/HackGT/auth/blob/1e713d703aaa29e67e611e846370bded94e8353d/server/api/api.ts#L24

This problem was solved in the `auth.ts` code from registration by [validating the host name and port before using them](https://github.com/HackGT/registration/blob/c64a7e7a15b19c06f0017070cd3ddff45798e3aa/server/routes/auth.ts#L314).

**Comment by illegalprime** [comment]
I don't think this is a bug, can you take a look at #2 ? I don't know express.

**Comment by illegalprime** [comment]
The reason I don't think it's one is because if the host header was forged then they'd just go to the wrong link, and the auth cookie that got created won't be visible to the bad host.

**Comment by petschekr** [comment]
Just left a comment on #2.

That's true it won't authenticate but it could allow for phishing if the attacker's site looks like ours and it won't be very suspicious because our own site sent the user there.

**Comment by illegalprime** [comment]
@petschekr I think the API is confusing, all this does is given a callback URL return a URL that you can go to to authenticate your user. So if a phony site looks like ours and sends them to this auth page then they'll enter their info, be redirected to the attacker, but the attacker wouldn't have gained any information.

You can do the same thing with Georgia Tech's auth page but you won't gain the password or 🍪s.

**Comment by petschekr** [comment]
Ok so this might be a bit far fetched but consider this:

* User is trying to register for HackGT
* Registration sends an API request to auth asking for the URL to find the login page at and adds a redirect URL
* Man in the middle, malware on the machine, cosmic ray bit flips, etc. sets the `Host` header of the API request to `google.com`.
* Because auth doesn't check that it's actually being served via that address from `Host`, the server emits `https://google.com/login?callback=https%3A%2F%2Fregistration.hack.gt`
* User then gets sent to `google.com` instead of `auth.hack.gt` to log in. Google in this case is harmless and will throw a 404 but if the `Host` header is instead set to a phishing site that looks like `auth.hack.gt` or serves malware, or simply wants ad views, the user would be none the wiser.

**Comment by illegalprime** [comment]
@petschekr our servers and clients would connect via SSL to auth.hack.gt, which is hard to spoof through man in the middle.

Short answer is I'm for it but I don't know how to do it. How do you chain middleware in Express?

```javascript
app.use('/graphql', validateAndCacheHosts, graphqlApi)
```

Doesn't work (`graphqlApi` is middleware). Maybe:

```javascript
app.use('/graphql', validateAndCacheHosts);
app.use('/graphql', graphqlApi);
```

But I don't know if Express makes garauntees about order.

**Comment by petschekr** [comment]
It should work exactly like [here](https://github.com/HackGT/registration/blob/c64a7e7a15b19c06f0017070cd3ddff45798e3aa/server/routes/auth.ts#L393). Express middleware is executed serially so it should work. You may have to do `app.route("/graphql").all(validateAndCacheHosts, graphqlApi);`.

**Comment by illegalprime** [comment]
@petschekr the example you gave was using `post`, I'll try the line you wrote though.

**Comment by petschekr** [comment]
I think it should work regardless of HTTP method
